import Head from 'next/head';
import Header from '../components/Header';
import Nav from '../components/Nav';
import Results from '../components/Results';
import requests from '../utils/requests';

export default function Home(props) {
  const {serverData} = props;

  return (
    <>
      <Head>
        <title>Movi</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
        <meta
          name='description'
          content="Welcome to Movi, If you enjoy movies you've come to the right place, Movi is an online database containing information and statistics about movies."
        />
      </Head>
      <div>
        <Header />
        <Nav />
        <Results serverData={serverData} />
      </div>
    </>
  );
}

export const getServerSideProps = async (context) => {
  const genre = context.query.genre;

  let url;

  switch (genre) {
    case 'fetchUpcomingMovies':
      url = `https://api.themoviedb.org/3${requests[genre]?.url}`;

      break;
    case 'fetchTopRated':
      url = `https://api.themoviedb.org/3${requests[genre]?.url}`;

      break;
    case 'fetchPopularMovies':
      url = `https://api.themoviedb.org/3${requests[genre]?.url}`;
      break;

    default:
      url = `https://api.themoviedb.org/3${requests[genre]?.url || requests.fetchTrending.url}`;
  }

  const res = await fetch(url);

  const serverData = await res.json();

  return {props: {serverData: JSON.stringify(serverData.results)}};
};
